version: '3.9'

services:

  app:
    build:
      context: ./
      dockerfile: manifest/docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www

  web:
    build:
      context: ./
      dockerfile: manifest/docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80
